apiVersion: apps/v1
kind: Deployment
metadata:
  name: okt1hch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okt1hch
  template:
    metadata:
      labels:
        app: okt1hch
    spec:
      containers:
      - image: okteto.dev/okt1hch:latest
        name: okt1hch
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "3812c417-03ed-4576-9406-880a0321b778"
        - name: Vless_Path
          value: "/3812c417-03ed-4576-9406-880a0321b778-vless"
        - name: Vmess_UUID
          value: "3812c417-03ed-4576-9406-880a0321b778"
        - name: Vmess_Path
          value: "/3812c417-03ed-4576-9406-880a0321b778-vmess"
        - name: Trojan_UUID
          value: "3812c417-03ed-4576-9406-880a0321b778"
        - name: Trojan_Path
          value: "/3812c417-03ed-4576-9406-880a0321b778-trojan"
        - name: SS_UUID
          value: "3812c417-03ed-4576-9406-880a0321b778"
        - name: SS_Path
          value: "/3812c417-03ed-4576-9406-880a0321b778-ss"
        - name: Share_Path
          value: "/3812c417-03ed-4576-9406-880a0321b778-share"
