apiVersion: v1
kind: Service
metadata:
  name: okt1hch
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okt1hch"
    port: 8080
  selector:
    app: okt1hch
